# Generate vignettes/themakr-vignette.css from the CTTIR/themakR package.
#
# The vignette's look IS themakR's: this script reads themakR's own
# `_pkgdown.yml` design tokens and compiles its own `pkgdown/extra.scss`
# (the suite source of truth, https://github.com/CTTIR/themakR), then writes
# the result to a committed CSS file the vignette references. That keeps the
# vignette CRAN-buildable (no build-time dependency on the GitHub-only themakR)
# while staying genuinely sourced from themakR — re-run this after installing a
# newer themakR to refresh the styling.
#
#   pak::pak("CTTIR/themakR"); source("data-raw/make_vignette_css.R")

if (!requireNamespace("themakR", quietly = TRUE)) {
  stop("Install CTTIR/themakR first: pak::pak(\"CTTIR/themakR\")")
}
stopifnot(requireNamespace("sass", quietly = TRUE),
          requireNamespace("yaml", quietly = TRUE))

scss_path <- system.file("pkgdown", "extra.scss", package = "themakR")
yml_path  <- system.file("pkgdown", "_pkgdown.yml", package = "themakR")
if (!nzchar(scss_path) || !nzchar(yml_path)) {
  stop("themakR is installed but its pkgdown/extra.scss / _pkgdown.yml are missing.")
}

# --- themakR design tokens (from its _pkgdown.yml bslib block) --------------
bslib_cfg <- yaml::read_yaml(yml_path)$template$bslib
gfont <- function(x, fallback) {
  fam <- if (is.list(x)) x[["google"]] %||% x[["family"]] else x
  if (is.null(fam) || !nzchar(fam)) return(fallback)
  sprintf("'%s', %s", fam, fallback)
}
`%||%` <- function(a, b) if (is.null(a)) b else a

bg        <- bslib_cfg$bg %||% "#fafafa"
fg        <- bslib_cfg$fg %||% "#212121"
primary   <- bslib_cfg$primary %||% "#1565c0"
radius    <- bslib_cfg$`border-radius` %||% "0.375rem"
sans_stack <- "system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, sans-serif"
base_font <- gfont(bslib_cfg$base_font, sans_stack)
head_font <- gfont(bslib_cfg$heading_font, sans_stack)
code_font <- gfont(bslib_cfg$code_font,
                   "'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace")

# --- minimal Bootstrap context themakR's extra.scss expects -----------------
# extra.scss references $primary, $font-family-monospace, $border-radius-sm,
# tint-color() and media-breakpoint-down(); supply just those so its rules
# compile standalone (no full Bootstrap bundle, keeping the output tiny).
prelude <- sprintf('
$primary: %s;
$font-family-monospace: %s;
$border-radius-sm: 0.25rem;
@function tint-color($color, $weight) { @return mix(white, $color, $weight); }
@mixin media-breakpoint-down($name) { @media (max-width: 575.98px) { @content; } }
', primary, code_font)

# --- themakR base palette/type, applied to the vignette body ----------------
base_rules <- sprintf('
body {
  background-color: %s;
  color: %s;
  font-family: %s;
}
h1, h2, h3, h4, h5, h6 { font-family: %s; color: %s; }
a { color: %s; }
code, kbd, pre, samp { font-family: $font-family-monospace; }
', bg, fg, base_font, head_font, fg, primary)

compiled <- sass::sass(list(prelude, base_rules, sass::sass_file(scss_path)))

header <- paste0(
  "/* DO NOT EDIT BY HAND.\n",
  " * Generated by data-raw/make_vignette_css.R from CTTIR/themakR ",
  as.character(utils::packageVersion("themakR")), "\n",
  " * (its _pkgdown.yml tokens + compiled pkgdown/extra.scss).\n",
  " * The vignette therefore carries the genuine themakR suite identity. */\n\n"
)

out_path <- file.path("vignettes", "themakr-vignette.css")
writeLines(paste0(header, as.character(compiled)), out_path)
message("Wrote ", out_path, " (", file.info(out_path)$size, " bytes) from themakR ",
        as.character(utils::packageVersion("themakR")))
